import React from 'react';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

import { SocketProvider } from '~/components/providers/socket';
import { QueryProvider } from '~/components/providers/query';
import { StoreProvider } from '~/components/providers/store/store-provider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <StoreProvider>
            <SocketProvider>{children}</SocketProvider>
          </StoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
