import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

import { SocketProvider } from './socket/SocketProvider';

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
   <html lang="en">
     <body>
       <SocketProvider>{children}</SocketProvider>
     </body>
   </html>
 );
}
